-- 1) users
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    provider VARCHAR(20) NOT NULL,
    social_id VARCHAR(20) NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    profile_image_url VARCHAR(255),
    role VARCHAR(20) NOT NULL CHECK (role IN ('USER', 'ADMIN')),
    created_at TIMESTAMP NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE', 'WITHDRAWN', 'BANNED')),
    deleted_at TIMESTAMP
);

-- 2) player
CREATE TABLE IF NOT EXISTS player (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_ko VARCHAR(255),
    name_en VARCHAR(255),
    birth_date DATE,
    nationality VARCHAR(255),
    bats VARCHAR(255) CHECK (bats IN ('LEFT', 'RIGHT', 'SWITCH')),
    throws VARCHAR(255) CHECK (throws IN ('LEFT', 'RIGHT')),
    debut_date DATE,
    retire_date DATE,
    link VARCHAR(255)
);

-- 3) content
CREATE TABLE IF NOT EXISTS content (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform VARCHAR(20) NOT NULL CHECK (platform IN ('article', 'video', 'youtube')),
    press VARCHAR(100) NOT NULL,
    url VARCHAR(500),
    title VARCHAR(300) NOT NULL,
    body TEXT NOT NULL,
    creator VARCHAR(100) NOT NULL,
    published_at TIMESTAMP NOT NULL,
    crawled_at TIMESTAMP NOT NULL,
    has_video BOOLEAN NOT NULL,
    representative_image_url TEXT,
    image_count BIGINT NOT NULL,
    like_count BIGINT NOT NULL,
    comment_count BIGINT NOT NULL
);

-- 4) content_comment
CREATE TABLE IF NOT EXISTS content_comment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    comment TEXT NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_content_comment_content FOREIGN KEY (content_id) REFERENCES content(id),
    CONSTRAINT fk_content_comment_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- 5) content_like
CREATE TABLE IF NOT EXISTS content_like (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('LIKE', 'CANCEL')),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_content_like_content FOREIGN KEY (content_id) REFERENCES content(id),
    CONSTRAINT fk_content_like_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- 6) image
CREATE TABLE IF NOT EXISTS image (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id BIGINT NOT NULL,
    image_url TEXT NOT NULL,
    order_index BIGINT,
    CONSTRAINT fk_image_content FOREIGN KEY (content_id) REFERENCES content(id)
);

-- 7) user_content_action
CREATE TABLE IF NOT EXISTS user_content_action (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    platform VARCHAR(30) NOT NULL CHECK (platform IN ('article', 'video', 'youtube')),
    action_type VARCHAR(30) NOT NULL CHECK (action_type IN ('VIEW', 'LIKE', 'LIKE_CANCLE', 'COMMENT', 'COMMENT_DELETE')),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_user_content_action_content FOREIGN KEY (content_id) REFERENCES content(id),
    CONSTRAINT fk_user_content_action_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- 8) player_content_map (composite PK)
CREATE TABLE IF NOT EXISTS player_content_map (
    player_id BIGINT NOT NULL,
    content_id BIGINT NOT NULL,
    confidence BIGINT,
    PRIMARY KEY (player_id, content_id),
    CONSTRAINT fk_player_content_map_player FOREIGN KEY (player_id) REFERENCES player(id),
    CONSTRAINT fk_player_content_map_content FOREIGN KEY (content_id) REFERENCES content(id)
);

-- 9) user_favorite_players (composite PK)
CREATE TABLE IF NOT EXISTS user_favorite_players (
    player_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (player_id, user_id)
);

-- indexes
CREATE INDEX IF NOT EXISTS idx_content_comment_content_id ON content_comment(content_id);
CREATE INDEX IF NOT EXISTS idx_content_comment_user_id ON content_comment(user_id);
CREATE INDEX IF NOT EXISTS idx_content_like_content_id ON content_like(content_id);
CREATE INDEX IF NOT EXISTS idx_content_like_user_id ON content_like(user_id);
CREATE INDEX IF NOT EXISTS idx_image_content_id ON image(content_id);
CREATE INDEX IF NOT EXISTS idx_user_content_action_content_id ON user_content_action(content_id);
CREATE INDEX IF NOT EXISTS idx_user_content_action_user_id ON user_content_action(user_id);
